apiVersion: v1
kind: Namespace
metadata:
  name: sale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: sale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: momtaz/auth:1-alpine
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: "mongodb://auth-mongo-svc:27017/auth-db"
            - name: JWT_SECRET
              value: "secret"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: sale
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3001
      targetPort: 3001
