apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: momtaz/order
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              value: "mongodb://order-mongo-svc:27017/order-db"
            - name: JWT_SECRET
              value: "secret"
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order
  ports:
    - name: order
      protocol: TCP
      port: 3002
      targetPort: 3002
