apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
  namespace: sale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: momtaz/product:3-alpine
          env:
            - name: PORT
              value: "3003"
            - name: MONGO_URI
              value: "mongodb://product-mongo-svc:27017/product-db"
            - name: JWT_SECRET
              value: "secret"
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: sale
spec:
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3003
      targetPort: 3003
